# Generated by Django 5.0.7 on 2024-07-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='date_last_updated',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='deleted',
        ),
    ]
